# Generated by Django 4.0.4 on 2022-06-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('correo', models.EmailField(blank=True, max_length=100)),
                ('clave', models.CharField(blank=True, max_length=50)),
                ('estado', models.BooleanField()),
            ],
        ),
    ]
